<?php

require 'vendor/autoload.php';

use Symfony\Component\DomCrawler\Crawler;

// Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/
$ch = curl_init();

curl_setopt($ch, CURLOPT_URL, 'https://a836-pts-access.nyc.gov/care/datalets/datalet.aspx?mode=asmt_fin_2020&UseSearch=no&pin=4022900015');
curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
curl_setopt($ch, CURLOPT_CUSTOMREQUEST, 'GET');	
curl_setopt($ch, CURLOPT_ENCODING, 'gzip, deflate');

$headers = array();
$headers[] = 'Connection: keep-alive';
$headers[] = 'Cache-Control: max-age=0';
$headers[] = 'Sec-Ch-Ua: Google Chrome 76';
$headers[] = 'Upgrade-Insecure-Requests: 1';
$headers[] = 'User-Agent: Mozilla/5.0 (iPad; CPU OS 11_0 like Mac OS X) AppleWebKit/604.1.34 (KHTML, like Gecko) Version/11.0 Mobile/15A5341f Safari/604.1';
$headers[] = 'Sec-Fetch-Dest: document';
$headers[] = 'Sec-Fetch-Mode: navigate';
$headers[] = 'Sec-Fetch-User: ?1';
$headers[] = 'Sec-Origin-Policy: 0';
$headers[] = 'Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3';
$headers[] = 'Sec-Fetch-Site: none';
$headers[] = 'Accept-Encoding: gzip, deflate, br';
$headers[] = 'Accept-Language: en-US,en;q=0.9';
$headers[] = 'Cookie: ASP.NET_SessionId=utk4gkq2vxxbrwidxk3obbrv';
curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);

$html = curl_exec($ch);

$crawler = new Crawler($html);

$result = $crawler->filter('#datalet_div_7 .DataletData')->each(function (Crawler $node, $i) {
	return $node->text();
});

if (empty($result)) die('completed');

$result = array_chunk($result, 3);

foreach ($result as $key => $value) {
	echo $value[0];
	echo $value[1];
	echo $value[2];
	echo "\n";
}

if (curl_errno($ch)) {
    echo 'Error:' . curl_error($ch);
}

curl_close($ch);
